# Generated by Django 4.0.6 on 2022-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
