# Generated by Django 4.0.6 on 2022-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnt', '0002_customerprofile_slug_vendorprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
